### PR TITLE
Fix the non-static method call by making the method static

### PR DESCRIPTION
**Pull request by valendesigns**

### CODE REVIEW

**Comment by fjarrett** [comment]
@valendesigns Is this the PR that was being discussed over email with Emma and Susan?

**Comment by valendesigns** [comment]
Correct

**Comment by fjarrett** [comment]
@valendesigns I thought Emma was talking about applying bug fix for a shortcode issue that GEM had? The one you fixed in https://github.com/godaddy/wp-godaddy-email-marketing/pull/12/commits/1b3e429b7f20b72c8b3028909ca996a3ccac904e#diff-a13df17493f1bd26fd7302ac0348a486

**Comment by valendesigns** [comment]
All issues should now be addressed in this PR.

**Pull request merged**
